# Generated by Django 5.2.3 on 2025-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_contactnews_news_cantact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cantact',
        ),
        migrations.DeleteModel(
            name='ContactNews',
        ),
    ]
